services:
  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8070:8070"

  worker:
    build: ./backend
    command: celery -A app.tasks worker -l info -c 4
    env_file: .env
    depends_on:
      - redis

  beat:
    build: ./backend
    command: celery -A app.tasks beat -l info
    env_file: .env
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3070:3070"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
